Repository GopediaPro/neunexus_login, pull requests merged in 2025-08, with the labels that each got.

#104 Fix: 주문관리 행 추가 및 생성 오류 수정
  client/src/api/order/postBulkDownFormOrders.ts
  client/src/api/order/postDownFormOrdersDate.ts
  client/src/constant/apiEndPoint.ts
  client/src/contexts/OrderContext.tsx
  client/src/hooks/orderManagement/useOrderCreate.ts
  client/src/hooks/orderManagement/useOrderGridActions.ts
Labels: 🐞Bug

#119 Feat: macro 버튼 임시 UI 추가, '배치 정보 조회' 커스텀 색상 적용
  client/src/components/ui/Modal/BatchInfoModal.tsx
  client/src/pages/Order/OrderToolbar.tsx
Labels: Fix

#124 Refactor: 주문관리 - 스마일배송 request_id value changed to created_user
  client/src/components/ui/Modal/SmileMacroBulkUploadModal.tsx
Labels: 🖥️ API
