Repository GopediaPro/neunexus_login, pull requests merged in 2025-06, with the labels that each got.

#15 Feat: toggle 컴포넌트 추가
  README.md
  client/src/components/ui/Toggle.tsx
  client/src/stories/Toggle.stories.tsx
Labels: ✨ Feat, 🎨 Html&Css

#18 Feat: 상품 등록 폼 UI 추가
  client/src/components/ProductForm.tsx
Labels: 🎨 Html&Css

#21 Feat: private router 추가
  client/src/components/layout/PrivateRoute.tsx
  client/src/components/layout/PublicRoute.tsx
  client/src/routing.tsx
Labels: ✨ Feat

#28 Feat: 메인페이지 중앙 컨텐츠 구현
  client/public/image/chart.svg
  client/public/image/document.svg
  client/public/image/edit.svg
  client/public/image/label.svg
  client/public/image/order.svg
  client/public/image/plus.svg
  client/public/image/print.svg
  client/public/image/product.svg
  client/public/image/service.svg
  client/public/image/upload.svg
  client/src/components/Icon.tsx
  client/src/components/auth/AuthForm.tsx
  client/src/components/main/Layout/ContentLayout.tsx
  client/src/components/main/Layout/HeaderLayout.tsx
  client/src/components/main/Layout/RightSidebarLayout.tsx
  client/src/components/main/LeftMenuButton.tsx
  client/src/components/mainpage/common/MenuBox.tsx
  client/src/components/mainpage/common/StatusCard.tsx
  client/src/components/mainpage/common/ViewAllButton.tsx
  client/src/components/mainpage/dashboard/CSStatus.tsx
  client/src/components/mainpage/dashboard/Dashboard.tsx
  client/src/components/mainpage/dashboard/InventoryStatus.tsx
  client/src/components/mainpage/dashboard/ProductStatus.tsx
  client/src/components/mainpage/dashboard/SalesStatus.tsx
  client/src/components/mainpage/dashboard/StatsDashboard.tsx
  client/src/components/mainpage/layout/ContentLayout.tsx
  client/src/components/mainpage/layout/HeaderLayout.tsx
  client/src/components/mainpage/layout/LeftSidebarLayout.tsx
  client/src/components/mainpage/layout/RightSidebarLayout.tsx
  client/src/components/mainpage/sidebar/LeftMenuButton.tsx
  client/src/components/mainpage/sidebar/MenuLayout.tsx
  client/src/components/mainpage/sidebar/NotiContainer.tsx
  client/src/components/mainpage/sidebar/OrgContainer.tsx
  client/src/components/mainpage/sidebar/ScheduleContainer.tsx
  client/src/index.css
  client/src/mocks/dummy/menu.ts
  client/src/mocks/dummy/sidebar.ts
  client/src/mocks/dummy/stats.ts
  client/src/mocks/dummy/status.ts
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/services/keycloakLogin.ts
  client/src/services/keycloakSignup.ts
  client/src/services/keycloakToken.ts
  client/src/services/keycloakUser.ts
  client/src/share/icons/OrderIcon.tsx
  client/src/share/icons/ProductIcon.tsx
  client/src/share/icons/ServiceIcon.tsx
  client/src/share/types/auth.types.ts
  client/src/share/types/sidebar.types.ts
  client/src/share/types/stats.types.ts
  client/src/share/types/user.types.ts
  client/src/utils/keycloakConfig.ts
  client/tailwind.config.js
Labels: 🎨 Html&Css
